### ISSUE TITLE
Problem in error handling

### ISSUE THREAD

**Issue by shaibt** [Datahero/node-eventbrite#18]
Hi, 

I think there's a problem when receiving an error from the Eventbrite API - in the code for handling the response (starting in line 106 of eventbrite_v3.js).

Once `parsedResponse.error` results in true the error retuned to the callback is (line 110):
`callback(new Error(parsedResponse.error + '' + parsedResponse.error_description))`

while I think it should have been:
`return callback(helpers.createEventbriteError(parsedResponse));`

This last line actually appears in line 117 but seems to never be called (unless I'm missing something).
The first callback returns a "message" only error object that doesn't hold the http response code or description separately.

**Comment by ibash** [comment]
Happy to accept pull requests :)

**Comment by toddpress** [comment]
since resolved, correct? 👍  👎  ... @shaibt 🥇

**Comment by shaibt** [comment]
Correct @toddpress  - @ibash has merged and released in v0.0.19

**Comment by ibash** [comment]
Thanks!
